name: Test Build on PR

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '.github/**'
      - 'README.md'

permissions:
  pull-requests: read
  contents: read

jobs:
  build-pr-code:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build command
        run: npm run build